// <auto-generated />
using System;
using ComputerStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerStore.Data.Migrations
{
    [DbContext(typeof(ComputerStoreDbContext))]
    partial class ComputerStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerStore.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Central Processing Units",
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Graphics Processing Units",
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Memory modules",
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 4,
                            Description = "SSDs and HDDs",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mainboards",
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 6,
                            Description = "PSUs",
                            Name = "Power Supply"
                        },
                        new
                        {
                            Id = 7,
                            Description = "PC Cases",
                            Name = "Case"
                        },
                        new
                        {
                            Id = 8,
                            Description = "CPU and case coolers",
                            Name = "Cooling"
                        });
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Intel",
                            Website = "https://www.intel.com"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "AMD",
                            Website = "https://www.amd.com"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "NVIDIA",
                            Website = "https://www.nvidia.com"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Name = "Corsair",
                            Website = "https://www.corsair.com"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Taiwan",
                            Name = "G.Skill",
                            Website = "https://www.gskill.com"
                        },
                        new
                        {
                            Id = 6,
                            Country = "South Korea",
                            Name = "Samsung",
                            Website = "https://www.samsung.com"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "WD",
                            Website = "https://www.westerndigital.com"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "Seagate",
                            Website = "https://www.seagate.com"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Taiwan",
                            Name = "ASUS",
                            Website = "https://www.asus.com"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Taiwan",
                            Name = "MSI",
                            Website = "https://www.msi.com"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Germany",
                            Name = "be quiet!",
                            Website = "https://www.bequiet.com"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Sweden",
                            Name = "Fractal Design",
                            Website = "https://www.fractal-design.com"
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            Name = "NZXT",
                            Website = "https://www.nzxt.com"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Austria",
                            Name = "Noctua",
                            Website = "https://www.noctua.at"
                        });
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PcPartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PcPartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.PcPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PcParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 1,
                            Name = "Intel Core i9-14900K",
                            Price = 589.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 1,
                            Name = "Intel Core i5-14600K",
                            Price = 299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 2,
                            Name = "AMD Ryzen 9 7950X",
                            Price = 549.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 2,
                            Name = "AMD Ryzen 5 7600X",
                            Price = 229.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 3,
                            Name = "NVIDIA GeForce RTX 4090",
                            Price = 1599.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 3,
                            Name = "NVIDIA GeForce RTX 4070",
                            Price = 599.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 2,
                            Name = "AMD Radeon RX 7900 XTX",
                            Price = 999.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 2,
                            Name = "AMD Radeon RX 7600",
                            Price = 269.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 4,
                            Name = "Corsair Vengeance 32GB DDR5-6000",
                            Price = 139.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 5,
                            Name = "G.Skill Trident Z5 16GB DDR5-5600",
                            Price = 79.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 6,
                            Name = "Samsung 990 Pro 1TB NVMe",
                            Price = 109.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 7,
                            Name = "WD Black SN850X 2TB NVMe",
                            Price = 179.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 8,
                            Name = "Seagate Barracuda 4TB HDD",
                            Price = 74.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 9,
                            Name = "ASUS ROG Maximus Z790 Hero",
                            Price = 599.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 10,
                            Name = "MSI MAG B650 TOMAHAWK WIFI",
                            Price = 229.99m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 4,
                            Name = "Corsair RM1000x 1000W 80+ Gold",
                            Price = 189.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 11,
                            Name = "be quiet! Straight Power 850W",
                            Price = 149.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 12,
                            Name = "Fractal Design Torrent",
                            Price = 179.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 13,
                            Name = "NZXT H510 Flow",
                            Price = 99.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 14,
                            Name = "Noctua NH-D15",
                            Price = 99.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufacturerId = 4,
                            Name = "Corsair H150i Elite LCD",
                            Price = 259.99m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("ComputerStore.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@computerstore.bg",
                            PasswordHash = "YP50QG5/NT7ZefNQ8vu2ouhpCl+n0bDDKYPR2LP5X2c=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Order", b =>
                {
                    b.HasOne("ComputerStore.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.OrderItem", b =>
                {
                    b.HasOne("ComputerStore.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStore.Data.Models.PcPart", "PcPart")
                        .WithMany("OrderItems")
                        .HasForeignKey("PcPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PcPart");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.PcPart", b =>
                {
                    b.HasOne("ComputerStore.Data.Models.Category", "Category")
                        .WithMany("PcParts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStore.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany("PcParts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Category", b =>
                {
                    b.Navigation("PcParts");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Manufacturer", b =>
                {
                    b.Navigation("PcParts");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.PcPart", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ComputerStore.Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
